In [4]:
from pupper.HardwareInterface import HardwareInterface
from pupper.Config import PWMParams, ServoParams
import numpy as np
import re
import time

from calibrate_servos import get_motor_name, get_motor_setpoint, degrees_to_radians, step_until, overwrite_ServoCalibration_file

In [9]:
hardware_interface = HardwareInterface()
leg_index = 1

set_point = 0
axis = 0
hardware_interface.set_actuator_position(
                    degrees_to_radians(set_point),
                    axis,
                    leg_index,
                )


set_point = 45
axis = 1
hardware_interface.set_actuator_position(
                    degrees_to_radians(set_point),
                    axis,
                    leg_index,
                )


set_point = 45
axis = 2
hardware_interface.set_actuator_position(
                    degrees_to_radians(set_point),
                    axis,
                    leg_index,
                )

In [8]:
print(hardware_interface.servo_params.neutral_angle_degrees)
hardware_interface.set_actuator_postions(
    degrees_to_radians(hardware_interface.servo_params.neutral_angle_degrees)
    )

[[  0.   0.   0.   0.]
 [ 45.  45.  45.  45.]
 [-45. -45. -45. -45.]]


In [14]:
hardware_interface = HardwareInterface()
leg_index = 2

set_point = 0
axis = 0
hardware_interface.set_actuator_position(
                    degrees_to_radians(set_point),
                    axis,
                    leg_index,
                )


set_point = 0
axis = 1
hardware_interface.set_actuator_position(
                    degrees_to_radians(set_point),
                    axis,
                    leg_index,
                )


set_point = 40
axis = 2
hardware_interface.set_actuator_position(
                    degrees_to_radians(set_point),
                    axis,
                    leg_index,
                )