In [12]:
from torch.distributions import Normal
from torch import tensor

mu = tensor([0.,0.,0.,0.]).reshape(-1)
sigma = tensor([1.,1.,1.,1.]).reshape(-1)


In [13]:
dis = Normal(mu, sigma)


In [18]:
dis.sample()

tensor([-0.2550, -0.7625, -0.7280, -0.0507])

In [30]:
import torch

s = tensor([[0.,0.,0.,0.]])
torch.unsqueeze(s,0)

tensor([[[0., 0., 0., 0.]]])

In [10]:
import numpy as np

GRAVITY = 9.8
IMU_data_range = {"acceleration":16 * GRAVITY, "angular velocity":2000, 
                    "RollPitchYaw":180, "Quaterions":1}

acceleration_range = np.array([IMU_data_range["acceleration"]]*3)
angular_velocity_range = np.array([IMU_data_range["angular velocity"]]*3)
RPY_range = np.array([IMU_data_range["RollPitchYaw"]]*3)
Quaterions_range = np.array([IMU_data_range["Quaterions"]]*4)

IMU_range = np.concatenate((acceleration_range, angular_velocity_range, RPY_range, Quaterions_range), axis=0)

IMU_range

array([1.568e+02, 1.568e+02, 1.568e+02, 2.000e+03, 2.000e+03, 2.000e+03,
       1.800e+02, 1.800e+02, 1.800e+02, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00])

In [4]:
import numpy as np

(np.array([1,]))

array([1])

In [ ]:
a = {"info": None}